name:                astrochart
version:             0.2.0.0
github:              tboye/astrochart
license:             GPL-2
author:              Luis Borjas Reyes

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/tboye/astrochart#readme>

dependencies:
- base >= 4.11 && < 10
- rio >= 0.1.12.0
- swiss-ephemeris >= 1.4.2.0
- diagrams
- diagrams-core
- diagrams-lib
- diagrams-contrib
- diagrams-svg
- SVGFonts >= 1.7.0.1 && < 1.8
- servant
- servant-server
- wai
- warp
- envy
- http-types
- http-api-data
- lucid
- servant-lucid
- interpolate
- cmark
- validation-selective
- selective
- time
- timezone-detect >= 0.3.0.0
- svg-builder
- unordered-containers
- case-insensitive
- wai-enforce-https
- math-functions
- sqlite-simple >= 0.4.18.0

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  astrochart-exe:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - astrochart
    - optparse-simple

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

tests:
  astrochart-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - astrochart
    - hspec
    - hspec-wai
    - hspec-wai-json
    - QuickCheck
    - hspec-golden
