name: "Build and Release to Heroku (Staging)"
on:
  push:
    branches: [ develop ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v13
      with:
        nix_path: nixpkgs=channel:nixos-21.05
    - name: Login to Heroku Container Registry
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run:
        heroku container:login
    - name: Build with nix and load into docker
      run:
        docker load < $(nix-build ./nix/docker.nix)
    - name: Push to container Registry
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        docker tag astrochart:latest registry.heroku.com/astrochart-staging/web
        docker push registry.heroku.com/astrochart-staging/web
    - name:  Release
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run:
        heroku container:release web -a astrochart-staging
